### ISSUE TITLE
Issue in cell 3?

### ISSUE THREAD

**Issue by jtoepp** [Poseyy/DatasetDaily#2]
Just cloned the dataset and opened the Jupyter Notebook. Ran first three cells but am running into an issue with cell 3--it could be something I am not seeing, though.

MSFT
AAPL
ORCL
IBM
INTC
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-38dad8860c2b> in <module>
     28     response = requests.get(url)
     29     response = response.json()
---> 30     df = pd.DataFrame(response['results'])
     31     df = df[df.period == 'Q']
     32     financials_dataframe = financials_dataframe.append(df, ignore_index=True)

KeyError: 'results'

**Comment by Poseyy** [comment]
Hi @jtoepp this results from you probably not putting an API Key in for the data provider. 

You can just download the dataset from our Google Drive link in the email or clone the repo and just use the dataset in a separate notebook or file. 

Some analysis will come from custom curated free sources, our own sensors, etc but others will come from sources like this.
